### ISSUE TITLE
Add websocket functionality to Phore RPC

### ISSUE THREAD

**Issue by meyer9** [phoreproject/rpc-proxy#2]
The basic workflow for a wallet requires notifications for blocks and transactions to wallets. For some wallet, this may look like the following:

1. Wallet requests next 10 addresses of HD wallet.
2. If those are all empty (no transactions), return.
3. If those are not empty, add transactions to list and go to 1.

We can figure out how many addresses of an HD wallet have been used using this method. All of this can be accomplished using `searchrawtransactions`. The next step the client should do is generate a [bloom filter](https://en.wikipedia.org/wiki/Bloom_filter) for watching these addresses.

--------------

Phore RPC Proxy needs to implement a feature using websockets where clients can subscribe to either an address, or a bloom filter of addresses to be notified of any transactions that occur through those addresses. There should also be an option to include transactions just added to the mempool, but not added to the blockchain yet.

# Specification

#### `subscribeBloom <bloomFilter> [includeMempool=false]`
This command will subscribe to any transactions that are included in the bloom filter provided.

#### `subscribeAddress <address> [includeMempool=false]`
This command will subscribe to a certain address.

#### `subscribeBlock`
This command will subscribe to any blocks that are staked.

#### `unsubscribeAll`
This command will cancel any subscriptions currently active.

The implementation should limit a connection to 50 of any type of subscription.

# Implementation

There will be a database that can be accessed by a cluster of websockets servers and provides notifications that expire. The easiest way I could think of to do this would be using Redis.

The only way to get notified of an event through the Phore daemon is through command-line callbacks.

Any time a block is added `-blocknotify=<cmd>`:
- Add transaction confirmed notifications to the database from any transactions in the block.
- Add a block mined notification to the database.

Each websocket server in the cluster will handle N number of connections.

When a transaction notification is received, the websocket server will send out the transaction to any clients subscribed using bloom filters or using an address.

When a block notification is received, the websocket server will send out the block to any clients subscribed to blocks.

Each websocket server will also keep track of each connections subscriptions which will be wiped when the client disconnects.

The implementation will rely heavily on the Phore RPC and should not use any methods other than the ones listed here: http://rpc.phore.io/

---

EDIT: changed URL to RPC proxy

**Comment by diofeher** [comment]
Being implemented on https://github.com/phoreproject/Phore-websockets

**Comment by meyer9** [comment]
Done by @diofeher in 4509d628083901a4235c71b076eec6e5a519847f
